name: tag
on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: .

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.PSBOT_GITHUB_TOKEN }}
        with:
          config-name: release-drafter.yml
          publish: true
